remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: "MAE 4190 Fast Robots"
description: "Recording my Fast Robots experience"
theme: jekyll-theme-midnight
include: ["docs"]
defaults:
  - scope:
      path: "docs"
    values:
      permalink: "/"
