remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: "Fast Robots"
description: "Documenting my Fast Robots journey!"
theme: jekyll-theme-cayman
include: ["docs"]
defaults:
  - scope:
      path: "docs"
    values:
      permalink: "/"
